name: make fish
  
  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: SetupRust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: 1.67
    - name: Install deps
      run: |
        sudo pip3 install pexpect
        brew install tmux
    - name: cmake
      run: |
        mkdir build && cd build
        cmake -DWITH_GETTEXT=NO ..
    - name: make
      run: |
        make
    - name: make test
      run: |
        make test
